name=EasyIR
version=1.0.0
author=OneDevelopmentPL
maintainer=
sentence=Simple IR library for popular microcontrollers.
paragraph=EasyIR is a simple library for sending and receiving IR signals on popular microcontrollers. It supports various protocols and is easy to use for beginners and advanced users alike.
category=Signal Input/Output
url=github.com/OneDevelopmentPL/EasyIR
architectures=avr,esp8266,esp32
