name=EasyIR
version=0.1.0
author=EasyIR Author
maintainer=
sentence=Prosta i dokładna biblioteka IR dla Arduino i ESP
paragraph=EasyIR to lekka biblioteka do przechwytywania i wysyłania sygnałów IR (NEC + surowe), działająca na Arduino, ESP8266 i ESP32. Zawiera proste przykłady dla Arduino IDE.
category=Signal Input/Output
url=
architectures=avr,esp8266,esp32